# Generated by Django 2.1.2 on 2018-11-16 01:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('raza', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=1)),
                ('descripcion', models.TextField(max_length=100)),
                ('imagen', models.ImageField(upload_to='rescatados')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('nacimiento', models.DateField(default=datetime.date.today)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15, null=True)),
                ('region', models.CharField(max_length=15)),
                ('ciudad', models.CharField(max_length=50)),
                ('vivienda', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='adopcion',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Mascota'),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Persona'),
        ),
    ]
