# Generated by Django 2.1.2 on 2018-11-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='estado',
            field=models.CharField(choices=[('', 'Seleccione un estado.'), ('r', 'Rescatado'), ('a', 'Adoptado'), ('d', 'Disponible')], default='r', max_length=1),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ciudad',
            field=models.CharField(choices=[('', 'Seleccione una ciudad'), ('santiago', 'Santiago'), ('maipo', 'Isla de Maipo'), ('valparaiso', 'Valparaiso'), ('vina', 'Viña del Mar'), ('calera', 'Calera'), ('rancagua', 'Rancagua'), ('san-fernando', 'San Fernando'), ('pichilemu', 'Pichilemu'), ('talca', 'Talca'), ('linares', 'Linares'), ('parral', 'Parral')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='region',
            field=models.CharField(choices=[('', 'Seleccione una región'), ('santiago', 'Región Metropolitana'), ('valparaiso', 'Región de Valparaiso'), ('rancagua', "Región del Libertador Bernardo O'Higgins"), ('maule', 'Región del Maule')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='persona',
            name='vivienda',
            field=models.CharField(choices=[('', 'Seleccione un tipo de vivienda'), ('casa-patio-grande', 'Casa con patio grande'), ('casa-patio-pequeño', 'Casa con patio pequeño'), ('casa-sin-patio', 'Casa sin patio'), ('departamento', 'Departamento')], default='', max_length=50),
        ),
    ]
